
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JComponent;
import javax.swing.LayoutStyle.ComponentPlacement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dash
 */
public class Details extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
	int[] pf;
    public Details() throws IOException {
        String d = ExcelReader.mainDataDetail();
pf = ExcelReader.pf();

        initComponents();
        jLabel1.setText(d);
        
        jLabel2.setText("Pass : "+pf[0]+ " \n Fail : "+pf[1]);
        
        PieChart.start(pf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(161)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel2)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 472, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(273)
        			.addComponent(jLabel1)
        			.addGap(65)
        			.addComponent(jLabel2)
        			.addContainerGap(295, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Details().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Details.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    
    class Slice {
    	  double value;
    	  Color color;

    	  public Slice(double value, Color color) {
    	    this.value = value;
    	    this.color = color;
    	  }
    	}

    	class MyComponent extends JComponent {
    	  Slice[] slices = { new Slice(46, Color.green), new Slice(54, Color.red)};

    	  MyComponent() {

    	  }
    	  public void paint(Graphics g) {
    	    drawPie((Graphics2D) g, getBounds(), slices);
    	  }

    	  void drawPie(Graphics2D g, Rectangle area, Slice[] slices) {
    	    double total = 0.0D;
    	    for (int i = 0; i < slices.length; i++) {
    	      total += slices[i].value;
    	    }

    	    double curValue = 0.0D;
    	    int startAngle = 0;
    	    for (int i = 0; i < slices.length; i++) {
    	      startAngle = (int) (curValue * 360 / total);
    	      int arcAngle = (int) (slices[i].value * 360 / total);

    	      g.setColor(slices[i].color);
    	      g.fillArc(area.x, area.y, area.width, area.height, startAngle, arcAngle);
    	      curValue += slices[i].value;
    	    }
    	  }
    	}

}
